// flow-typed signature: f2642b16df03ec9bf6084324db35f142
// flow-typed version: <<STUB>>/@firebase/app_v^0.1.10/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@firebase/app'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@firebase/app' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@firebase/app/coverage/browser/HeadlessChrome 64.0.3282 (Linux 0.0.0)/prettify' {
  declare module.exports: any;
}

declare module '@firebase/app/coverage/browser/HeadlessChrome 64.0.3282 (Linux 0.0.0)/sorter' {
  declare module.exports: any;
}

declare module '@firebase/app/dist/cjs/index' {
  declare module.exports: any;
}

declare module '@firebase/app/dist/cjs/src/firebaseApp' {
  declare module.exports: any;
}

declare module '@firebase/app/dist/esm/index' {
  declare module.exports: any;
}

declare module '@firebase/app/dist/esm/src/firebaseApp' {
  declare module.exports: any;
}

// Filename aliases
declare module '@firebase/app/coverage/browser/HeadlessChrome 64.0.3282 (Linux 0.0.0)/prettify.js' {
  declare module.exports: $Exports<'@firebase/app/coverage/browser/HeadlessChrome 64.0.3282 (Linux 0.0.0)/prettify'>;
}
declare module '@firebase/app/coverage/browser/HeadlessChrome 64.0.3282 (Linux 0.0.0)/sorter.js' {
  declare module.exports: $Exports<'@firebase/app/coverage/browser/HeadlessChrome 64.0.3282 (Linux 0.0.0)/sorter'>;
}
declare module '@firebase/app/dist/cjs/index.js' {
  declare module.exports: $Exports<'@firebase/app/dist/cjs/index'>;
}
declare module '@firebase/app/dist/cjs/src/firebaseApp.js' {
  declare module.exports: $Exports<'@firebase/app/dist/cjs/src/firebaseApp'>;
}
declare module '@firebase/app/dist/esm/index.js' {
  declare module.exports: $Exports<'@firebase/app/dist/esm/index'>;
}
declare module '@firebase/app/dist/esm/src/firebaseApp.js' {
  declare module.exports: $Exports<'@firebase/app/dist/esm/src/firebaseApp'>;
}
